parameters:

services:
  darwin.location_manager:
    class: HappyR\LocationBundle\Manager\LocationManager
    arguments: [@doctrine.orm.entity_manager,@zenstruck.slugify]


  darwin.location_type:
    class: HappyR\LocationBundle\Form\Type\Location
    arguments: [@darwin.location_manager, @happyr.google.api.geocode]
    tags:
      - { name: form.type, alias: location }


