parameters:
  happyr.location.geocoder.excessive.class: 'Happyr\LocationBundle\Service\ExcessiveGeocoder'
  happyr.location.geocoder.excessive.class2: 'Happyr\LocationBundle\Service\ExcessiveGeocoder'

services:
  happyr.location.location_manager:
    class: Happyr\LocationBundle\Manager\LocationManager
    arguments: [@doctrine.orm.entity_manager, @happyr.slugify.slugifier]


  happyr.location.location_type:
    class: Happyr\LocationBundle\Form\Type\LocationType
    arguments: [@happyr.location.location_manager, @bazinga_geocoder.geocoder]
    tags:
      - { name: form.type, alias: location }

  happyr.location.geocoder.excessive:
    class: '%happyr.location.geocoder.excessive.class%'
    arguments: [@bazinga_geocoder.geocoder]